<a href="https://colab.research.google.com/github/Hyprnx/Machine_Learning_2/blob/main/W1/To_Duc_Anh_HW_PCA_W1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create data and implement PCA algorithm then visualize each step like the below figure.

Implement PCA algorithm to reduce dimension (2D) of iris dataset (https://archive.ics.uci.edu/ml/datasets/iris), then visualize  the result.

Use PCA in sklearn to iris dataset and compare the result with the question 2.

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import plotly.express as px

In [2]:
iris = pd.read_csv('/content/iris.data',header=None)
iris.columns = ["sepal_length","sepal_width",
                'petal_length','petal_width','species']
iris

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
fig = px.scatter_3d(iris, x='sepal_length', y='sepal_width', z='petal_width',
              color='species')
fig.show()


In [4]:
def standardize_data(arr):   
    rows, columns = arr.shape
    
    standardizedArray = np.zeros(shape=(rows, columns))
    tempArray = np.zeros(rows)
    
    for column in range(columns):
        
        mean = np.mean(X[:,column])
        std = np.std(X[:,column])
        tempArray = np.empty(0)
        
        for element in X[:,column]:
            
            tempArray = np.append(tempArray, ((element - mean) / std))
 
        standardizedArray[:,column] = tempArray
    
    return standardizedArray

In [5]:
X = iris.iloc[:, 0:4].values
y = iris.species.values
X[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
X = standardize_data(X)

In [7]:
covariance_matrix = np.cov(X.T)
covariance_matrix

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

In [8]:
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

print("Eigenvector: \n",eigen_vectors,"\n")
print("Eigenvalues: \n", eigen_values, "\n")

Eigenvector: 
 [[ 0.52237162 -0.37231836 -0.72101681  0.26199559]
 [-0.26335492 -0.92555649  0.24203288 -0.12413481]
 [ 0.58125401 -0.02109478  0.14089226 -0.80115427]
 [ 0.56561105 -0.06541577  0.6338014   0.52354627]] 

Eigenvalues: 
 [2.93035378 0.92740362 0.14834223 0.02074601] 



In [9]:
sum_explained_variance = sum(eigen_values)
sum_explained_variance

4.026845637583895

In [10]:
explained_variance = []
for eigen_value in eigen_values:
    explained_variance.append(eigen_value/sum_explained_variance * 100)

print(explained_variance)

sum_explained_variance = np.cumsum(explained_variance)
for i in range(len(sum_explained_variance)):
    print(f'PC {i} will take {sum_explained_variance[i]}%')
     

[72.77045209380134, 23.03052326768065, 3.683831957627376, 0.5151926808906263]
PC 0 will take 72.77045209380134%
PC 1 will take 95.80097536148199%
PC 2 will take 99.48480731910936%
PC 3 will take 99.99999999999999%


In [13]:

fig = px.line(
    y = sum_explained_variance,
    x = ['PC 1','PC 2', 'PC 3', 'PC 4'],
    title='Explained variance vs Number of components',
    labels=dict(x="Principle Component", y="Sum Explained Variance")
)
fig.show()

In [17]:
for i in eigen_vectors:
    print(i.T[:][:3])

[ 0.52237162 -0.37231836 -0.72101681]
[-0.26335492 -0.92555649  0.24203288]
[ 0.58125401 -0.02109478  0.14089226]
[ 0.56561105 -0.06541577  0.6338014 ]


In [14]:
from sklearn.decomposition import PCA

X = iris.iloc[:, 0:4].values
y = iris.species.values

pca = PCA(n_components=3)
components = pca.fit_transform(X)

total_var = pca.explained_variance_ratio_.sum() * 100

fig = px.scatter_3d(
    components, x=0, y=1, z=2, color=iris['species'],
    title=f'Total Explained Variance: {total_var:.2f}%',
    labels={'0': 'PC 1', '1': 'PC 2', '2': 'PC 3'}
)
fig.show()