<a href="https://colab.research.google.com/github/Hyprnx/Machine_Learning_2/blob/main/W1/To_Duc_Anh_HW_PCA_W1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create data and implement PCA algorithm then visualize each step like the below figure.

Implement PCA algorithm to reduce dimension (2D) of iris dataset (https://archive.ics.uci.edu/ml/datasets/iris), then visualize  the result.

Use PCA in sklearn to iris dataset and compare the result with the question 2.

# SOME CHARTS WILL NOT SHOW UP HERE, FOR BETTER VISUALLY INSPECTION, I RECOMMENT OPEN GOOGLE COLAB AND RUN ALL FROM THERE! 

#DATA FILE IS GIVEN ON GITHUB AS WELL.

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import plotly.express as px

In [2]:
iris = pd.read_csv('/content/iris.data',header=None)
iris.columns = ["sepal_length","sepal_width",
                'petal_length','petal_width','species']
iris

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
fig = px.scatter_3d(iris, x='sepal_length', y='sepal_width', z='petal_width',
              color='species')
fig.show()


In [4]:
def standardize_data(arr):   
    rows, columns = arr.shape
    
    standardizedArray = np.zeros(shape=(rows, columns))
    tempArray = np.zeros(rows)
    
    for column in range(columns):
        
        mean = np.mean(X[:,column])
        std = np.std(X[:,column])
        tempArray = np.empty(0)
        
        for element in X[:,column]:
            
            tempArray = np.append(tempArray, ((element - mean) / std))
 
        standardizedArray[:,column] = tempArray
    
    return standardizedArray

In [5]:
X = iris.iloc[:, 0:4].values
y = iris.species.values
X[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
X = standardize_data(X)

In [7]:
covariance_matrix = np.cov(X.T)
covariance_matrix

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

In [8]:
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

print("Eigenvector: \n",eigen_vectors,"\n")
print("Eigenvalues: \n", eigen_values, "\n")

Eigenvector: 
 [[ 0.52237162 -0.37231836 -0.72101681  0.26199559]
 [-0.26335492 -0.92555649  0.24203288 -0.12413481]
 [ 0.58125401 -0.02109478  0.14089226 -0.80115427]
 [ 0.56561105 -0.06541577  0.6338014   0.52354627]] 

Eigenvalues: 
 [2.93035378 0.92740362 0.14834223 0.02074601] 



In [9]:
sum_explained_variance = sum(eigen_values)
sum_explained_variance

4.026845637583895

In [10]:
explained_variance = []
for eigen_value in eigen_values:
    explained_variance.append(eigen_value/sum_explained_variance * 100)

print(explained_variance)

sum_explained_variance = np.cumsum(explained_variance)
for i in range(len(sum_explained_variance)):
    print(f'PC {i} will take {sum_explained_variance[i]}%')
     

[72.77045209380134, 23.03052326768065, 3.683831957627376, 0.5151926808906263]
PC 0 will take 72.77045209380134%
PC 1 will take 95.80097536148199%
PC 2 will take 99.48480731910936%
PC 3 will take 99.99999999999999%


In [13]:

fig = px.line(
    y = sum_explained_variance,
    x = ['PC 1','PC 2', 'PC 3', 'PC 4'],
    title='Explained variance vs Number of components',
    labels=dict(x="Principle Component", y="Sum Explained Variance")
)
fig.show()

In [33]:
pc = 3

projection_matrix = (eigen_vectors.T[:][:pc]).T
X_pca = X.dot(projection_matrix)
X_pca

array([[ 2.66923088, -5.18088722, -2.50606121],
       [ 2.69643401, -4.6436453 , -2.48287429],
       [ 2.4811633 , -4.75218345, -2.30435358],
       [ 2.57151243, -4.62661492, -2.22827673],
       [ 2.59065822, -5.23621104, -2.40975624],
       [ 3.00809881, -5.68221692, -2.45652515],
       [ 2.49094166, -4.90871397, -2.10637596],
       [ 2.70145461, -5.05320922, -2.44407359],
       [ 2.46158369, -4.36493047, -2.14656917],
       [ 2.67166282, -4.73176885, -2.50796192],
       [ 2.83139678, -5.47980351, -2.65987045],
       [ 2.65510568, -4.98085502, -2.28578101],
       [ 2.58763574, -4.59987189, -2.47415275],
       [ 2.15207373, -4.40738428, -2.15591202],
       [ 2.78696275, -5.90006937, -2.91793499],
       [ 2.91688204, -6.25247172, -2.5799922 ],
       [ 2.77559721, -5.67377901, -2.51288205],
       [ 2.72579198, -5.1874288 , -2.44268107],
       [ 3.13458468, -5.6948152 , -2.76041362],
       [ 2.70491091, -5.46720523, -2.35598198],
       [ 3.02665406, -5.20635552, -2.704

In [34]:
x = X_pca[:,0]
y = X_pca[:,1]
z = X_pca[:,2]


fig = px.scatter_3d(X_pca, x=x, y=y, z=y)
fig.show()
x

array([2.66923088, 2.69643401, 2.4811633 , 2.57151243, 2.59065822,
       3.00809881, 2.49094166, 2.70145461, 2.46158369, 2.67166282,
       2.83139678, 2.65510568, 2.58763574, 2.15207373, 2.78696275,
       2.91688204, 2.77559721, 2.72579198, 3.13458468, 2.70491091,
       3.02665406, 2.78780751, 2.14920797, 3.06596138, 2.82948189,
       2.86492198, 2.87270222, 2.77959344, 2.74780353, 2.65553951,
       2.73411216, 3.02352547, 2.56501939, 2.69383109, 2.67166282,
       2.57974939, 2.82005413, 2.67166282, 2.3771228 , 2.75369177,
       2.61542942, 2.67026951, 2.32445182, 2.95948894, 2.99397362,
       2.70075795, 2.7064752 , 2.48705154, 2.77915962, 2.6696647 ,
       6.33761491, 5.96450224, 6.48452515, 5.32763799, 6.18020677,
       5.59106186, 6.05874149, 4.41131841, 6.09298623, 5.06402025,
       4.68514834, 5.58161121, 5.44547598, 5.94648693, 4.9893606 ,
       6.03286271, 5.59927593, 5.2674496 , 6.12338283, 5.15595656,
       6.04737595, 5.50938351, 6.32911512, 5.85970021, 5.81413

In [14]:
from sklearn.decomposition import PCA

X = iris.iloc[:, 0:4].values
y = iris.species.values

pca = PCA(n_components=3)
components = pca.fit_transform(X)

total_var = pca.explained_variance_ratio_.sum() * 100

fig = px.scatter_3d(
    components, x=0, y=1, z=2, color=iris['species'],
    title=f'Total Explained Variance: {total_var:.2f}%',
    labels={'0': 'PC 1', '1': 'PC 2', '2': 'PC 3'}
)
fig.show()